language: objective-c
os: osx
osx_image: xcode7.1
xcode_workspace: Kingfisher.xcworkspace
xcode_scheme: Kingfisher

script: xcodebuild -workspace Kingfisher.xcworkspace -scheme Kingfisher -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' clean test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty && exit ${PIPESTATUS[0]}
after_success:
    - bash <(curl -s https://codecov.io/bash)
